name: apc_app
description: An app that allows you to view and interact with the alphabet.
version: 0.0.1
homepage: https://github.com/bl4ckswordsman/abc_app

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

