name: "Release Build"

permissions:
  contents: write
  packages: write
  statuses: read

on:
  push:
    tags:
      - "v*"

env:
  APP_NAME: abc_app

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Set up Flutter
        run: flutter pub get
      - name: Generate files with Builder
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Build with Flutter
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        run: flutter build apk
      - name: Sign APK
        id: sign_apk
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: build/app/outputs/apk/release
          signingKey: ${{ secrets.SIGNING_KEYSTORE }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      - name: Add version to APK
        run: mv ${{ steps.sign_apk.outputs.signedFile }} ${{ env.APP_NAME }}-release-${{ env.RELEASE_VERSION }}.apk
      - name: Publish release APK
        uses: "mathieucarbou/marvinpinto-action-automatic-releases@latest"
        # uses: "marvinpinto/action-automatic-releases@latest" original repo with deprecated set-output
        with:
          repo_token: "${{ secrets.ABCAPP_PAT_TOKEN }}"
          prerelease: false
          files: ${{ env.APP_NAME }}-release-${{ env.RELEASE_VERSION }}.apk
